### ISSUE TITLE
Can I change which file manager app is used by "Open Download"?

### ISSUE THREAD

**Issue by llinfeng** [plateaukao/browser#132]
It took some guessing work to know what the "Open Download" icon does - if the "Files by Google" app is installed, it attempts to jump to the Download section there. Yet, when "Files by Google" is not installed, nothing happens. (I found this icon "Open Download" icon after tapping on the Settings icon from the toolbar, or, as below:)
![image](https://user-images.githubusercontent.com/5890407/175823480-dc9efd39-6a11-4e84-a067-40c4c842e234.png)

Is there a place to change this default behavior? I'd like to select a separate file manager, if possible. (And, it doesn't have to open the Download folder with that file manager. I assume if I keep that file manager running the background, it should remember to show me the download folder next time I jump to it.)

----

**Background** - I'm using Hisense A9, a phone wtih e-ink display. It does not have the full Google service components, and Hisense has no plan to make it happen. While I got the Files by Google app installed through with an apk file, it always crashes due to the lack of Google service components. This leaves the "Open Download" icon useless, and me wondering where are those downloaded files :)

**Comment by plateaukao** [comment]
Hi, @llinfeng 

Glad to know that you are using Hisense A9. I have A7, A5proc CC, and A5. Quite useful Eink phones from Hisense company. 

Although Hisense Eink phones does not have Google related apps nor Google service components, it does come with its own file explorer 文件管理. When user clicks on Open Download item, it should bring you to default 文件管理 app and show you the download folder files. Unless... you removed or disabled the default file explorer. 

Since I use Android system API to bring up whatever assigned on the device as file explorer, I am not sure how to allow user assign what they want; or how could user assign his preferred app to be system file explorer. When I find out why, I will update you more.
