### ISSUE TITLE
Navigation bar only selectable on page title text, not selectable w/ no page loaded

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/browser#136]
The URL navigation bar appears to be selectable only over existing page-title text, not within blank regions, rather than over the full width of the navigation dialogue.

If there's no page loaded or the title is blank, the navigation bar is not selectable at all.

This seems to be a change within the past release or two (where the page title display also changed). 

I'm observing this on v.9.2.0.

Expected behavior:  Tapping anywhere within the navigation URL bar will select the field and permit text input.

**Comment by plateaukao** [comment]
I re implemented toolbar, so the behavior is a bit different. I'll add the feature to focus on input bar when clicking on empty part of the toolbar.

**Comment by dredmorbius** [comment]
Thanks, that would be preferred.

I've noticed your tendency to revamp the UI, it's interesting to watch.

Example:  the incognito / standard mode indicator.  The dashed box is _much_ more easily distinguished than the bolded border.  I'd noticed you'd reverted to it w/ v.9.2.0

I'm still deciding what I think of the new settings button-based layout, though it's reasonable.

(I warm slowly to change.  I try not to reject it out of hand.  And I suspect this is your toy for playing, so give latitude for that as well.  Just noting that it's all being observed 😺 )

**Comment by plateaukao** [comment]
I re-wrote the whole toolbar because the new architecture is much easier to add new actions(buttons) or manipulating the UI. When adding an action, I needed to modify various places to make it work. It's very troublesome and error-prone. That usually prevents me from adding anything that I don't use personally. Also, the original OSS project I started with (FOSS browser) is very very old fashion, since it's created long time ago. Without doing some refactoring, or applying some new framework to make my coding life easier, my intention to maintain it will gradually go away. 

I tried not to impact most users' daily use by using the latest changes on my own for several days or weeks. However, you know, my usage does not present all the users. So it may be some issues here and there. :) 

Now that I already added an option, and default behavior is search full input string. And I also trigger input edit when clicking on empty part of toolbar. You can download the nightly build zip from https://github.com/plateaukao/browser, unzip it, and install it to try it out. I may wait another week to have a new release.

**Comment by plateaukao** [comment]
fixed in https://github.com/plateaukao/browser/releases/tag/v9.3.0
