### ISSUE TITLE
Start site is contacted even if already navigated away from it

### ISSUE THREAD

**Issue by licaon-kter** [plateaukao/browser#149]
9.4.1 F-Droid

I've changed search engine to DDG, nothing.

I've setup a non existing custom search engine, no joy.

I visit `f-droid.org`, site loads. In the background the browser tries to connect to `www.google.com` _(no, **this** site does not load anything from Google lol)_.

I click on a site link, ping, connection to `www.google.com`.

I close the browser.

I open the browser, a new tab appears that connects to `www.google.com`.

Is this intentional to leak the users IP/device/agent/browsing to Google? Is it a _"software bug, nothing can be done"_? What's up with this?

I'm seeing the connections via Netguard.

**Comment by plateaukao** [comment]
Please navigate to any website that you want it to be the default launched website in EinkBro, and click the button below. Then, it won't load Google anymore. :)
![image](https://user-images.githubusercontent.com/4084738/181206937-70acef43-bb70-445b-bc65-04f2a79faf32.png)

**Comment by plateaukao** [comment]
> Is this intentional to leak the users IP/device/agent/browsing to Google? Is it a "software bug, nothing can be done"? What's up with this?

No, it's not of any intention to leak users' IP/device/browsing to Google. Just thought Google search might be the first thing users will do when they open a browser. It can be easily changed to any other websites.

**Comment by licaon-kter** [comment]
Why isn't this in settings?

**Comment by plateaukao** [comment]
It's already in menu. It's faster to be set than going into Setting pages.
So far, there's no direct way to disable Start site. Although you can go into Settings > Behavior/UI and turn on **Show recently used bookmarks**, to replace start site.

> Why does it try to connect to a Start site even if I've opened another site?
This should not happen. If so, it's an issue. Could you elaborate your steps?

If you want to keep previously opened tabs whenever you launch EinkBro, you can turn on **save tabs** in Settings > Behavior/UI.

> /LE: using a search engine as a Start site confusingly sends the messages that one can change it via the Search engine setting.
I did not think of this though. However, I think it's better to put up Google search page than putting up my github page as the Start site. :)

> Start site reminds me of the old Desktop browsers Home button. ;( :)
Yes, that reminds me of that too. This design is from the original browser implementation of https://github.com/scoute-dich/browser. I did not change it because I haven't thought of a better presentation, and it did not bother me either so far.

**Comment by licaon-kter** [comment]
> It's already in menu. It's faster to be set than going into Setting pages.

You have a "Start Control" settings page that doesn't control the starting Start page :)

> This should not happen. If so, it's an issue. Could you elaborate your steps?

Start app, don't allow google connection via Netguard, write some URL, see it load, look in Netguard, the app tries to connect still. I guess it will timeout at some point.

> I did not think of this though. However, I think it's better to put up Google search page than putting up my github page as the Start site. :)

Use a search engine, but maybe popup a selector on first start? Use that as Search and Start, or only Search. 

/ps: I don't think it's better to use Google as anything. :)

**Comment by plateaukao** [comment]
> Start app, don't allow google connection via Netguard, write some URL, see it load, look in Netguard, the app tries to connect still. I guess it will timeout at some point.

Does this happen after you changed start site to other web? Could you give me some example urls? As far as I know, lots of websites have google ad or google analytics plugin installed. That may be the reason why it still tries to connect google sites.

![image](https://user-images.githubusercontent.com/4084738/181232560-e98c0517-c2ab-4e11-8ab0-0493c0c98f76.png)

When I try to link to yahoo and monitor http requests in Netguard, I don't see google connections.


> /ps: I don't think it's better to use Google as anything. :)

Feel free to set up a new start site. :)

**Comment by licaon-kter** [comment]
See OP again.

So I did not change the Start site, for now this is about the current behaviour.

**Comment by plateaukao** [comment]
>/LE: I can repro with any Start site, eg. Like set f-droid.org (block this Start site address), start app, write another URL say calyxos.org, see it load, navigate around the site... In background the app tries to connect to f-droid.org for another 3 minutes then gives up.

If you really don't like some site to be loaded when EinkBro is launched, you could try change url to about:blank, and set it as start site. Usually, people would set some websites they want to access the most often as start site, instead of some url they are blocked iwth netguard.

In current implementation, as you said, when it's launched, if not set with "save tabs", it would load start site by default. That's exactly start site implemented for.

>Not working as expected. Cleared app data, open, settings, "show recent bookm" toggled ON and "save last" as ON. Restart as asked. Force close app (just in case). Restart app... connects to www.google.com on start.

For "save tabs" to work, you need to navigate some web sites in first session. And then, the next time you launch EinkBro, it will remember last url tab you browsed, and open again for you. If you leave it as default start site, and re-open EinkBro again, it just remember start site (since that's the last url you tried to connect),

And for  "show recent bookmarks" to work, you need to have some bookmarks saved first, and use these bookmarks to browse for several times. That's how they got remembered, and be used when you try to create a new tab. (I found that it does not work for the first tab when launch EinkBro. For this, I might consider change the logic, or allow users to decide whether to show start site or recently accessed bookmarks).

In the end, I think what you really concerned is: Neither "start site" nor "google search" is a fit for your usage. Modifying to "about:blank" would be a better solution in current implementation.

**Comment by licaon-kter** [comment]
`about:blank` does it. But seems excessively complicated.

**Comment by plateaukao** [comment]
I'll check in the future whether there's better UI for first-time users to decide whether to set up a start site or leave it blank.
