### ISSUE TITLE
Page reserved height not working correctly

### ISSUE THREAD

**Issue by beelzebielsk** [plateaukao/browser#17]
I'm not seeing a difference when I set "page reserved height" to something small. I tried it at 80, 60, 40, 0. The reserved looks the same. I'm using it because on certain sites, I need more reserved height for some reason. Especially those with annoying headers or footers which stay fixed on the site. Here is one example where I need a smaller reserved height to navigate the page sing the page-up and page-down functions: https://twitter.com/ekverstania/status/1341338767001591808

EinkBro version: 8.7.2
Device: Onyx Boox Poke 2
Android: 9

**Comment by plateaukao** [comment]
Hi, @beelzebielsk 
Thanks for reporting this issue. I will investigate what might go wrong.

**Comment by plateaukao** [comment]
Hi, @beelzebielsk 
If you want to reserve a larger space due to fixed header or footer in Web page, please try value like 200, or 300 or even larger. As for there's no obvious difference between 80, 60, 40, and 0, that may be because on Onyx Boox Poke2, the size difference is small comparing to its physical screen size. 

By the way, sometimes I found that I have to manually touch the web content first, to make sure it really measures the web content height. If it's still not working for you, you can also try the same way too. :)

**Comment by beelzebielsk** [comment]
I tried 200 or 300 and started seeing a difference. It didn't occur to me to use larger numbers for some reason. What do the numbers mean? I thought it was a percentage of the screen.

**Comment by plateaukao** [comment]
it's the relative size unit used in code, we call them **dp**.
1 dp could mean 2 pixels, or 4 pixels, or even 8 pixels depending on device resolutions.

On devices with different screen size and different resolutions, **dp** should be displayed in the same physical size. However, on Onyx devices, the system is modified to support manipulating the app resolution. So it's not the normal case. That's why I ask you to try larger numbers.

**Comment by beelzebielsk** [comment]
I see. Thanks so much for the explanation.
