### ISSUE TITLE
App restarts(??) itself when switching light/dark theme of the device

### ISSUE THREAD

**Issue by senntore** [plateaukao/browser#24]
Bug:
When switching light/dark theme of the device outside of the app, the app either restart itself or closes all of the open tabs to change its theme.
Expected behavior:
The app should change it's theme based on device without disrupting the current open tabs.

Version 8.8.0
OS: Android 11
Downloaded from F-droid

Side note(not related to this issue): I was having trouble viewing embedded imgur video/gif in a website, tell me if I should open another issue for it.

**Comment by plateaukao** [comment]
About restarting the UI to reflect dark mode change, that's current implementation. I know it's better to have the behavior you said, but it will take a lot of effort to implement. Since changing dark mode should not be a frequent action, I would not put effort on this in near future. (you can leave this issue open until some day I find time to implement it)

As for not being able to view imgur video/gif, please open another issue, with reproducible website. I will look into it. Before that, you can try to turn off adblock feature to see if it's caused by adblocking.
