### ISSUE TITLE
[Bug] A layout adaptation problem

### ISSUE THREAD

**Issue by yuhuitech** [plateaukao/browser#39]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout/display. As shown in the figure below, on the toolbar configuration page, **some texts could not be seen fully**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 8.12.1, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts in this list, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.go to toolbar configuration settings
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128961149-f20019df-cb8e-4ce0-bad8-b637f2ba4b73.png" alt="Screenshot_1628648627 copy" width="250"/>

**Environment**

1. Version of EinkBro: 8.12.1
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by plateaukao** [comment]
Hi, @yuhuitech 

Usually, the layout works best when the system font size is in normal mode. If you enlarge them because of personal preference, it's hard to keep all the texts displayed correctly, concerning the screen size limitation and too large font size. 

If you really want to see all the texts in toolbar config dialog, you can try to build your own version by modifying the list item layout height here: https://github.com/plateaukao/browser/blob/4985b0689a1131857b2dc70957dd80bf1b60aaf4/app/src/main/res/layout/item_list_preference_multi_drag.xml#L31

Hope this helps. :)

**Comment by yuhuitech** [comment]
OK! Thank you so much! I will work on this. :)
