### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by RasaKh** [plateaukao/browser#6]
Hi,
I'm aware that the browser is intended for eink devices and dark mode is not necessary but it's so amazingly light and full of features and it makes an very nice daily driver for other devices too.
Are you planning on implementing it?
Thank you for this app, it's absolutely beautiful.

**Comment by plateaukao** [comment]
Hi, @RasaKh 

Glad to hear that it's useful to you. On normal phones, I mainly use Firefox (and turn on dark mode plugin). If I have time, I would definitely support dark mode. However, it needs some effort, since most icons now are fixed with white background and black lines. If I need to change UI, I need to make the app support Theme first; not to mention studying how to make the web content support dark mode. 

I will try to do it, but not any time soon.
