### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#61]
Not an issue, but a question.

Is it possible to install extensions? (the ones i use for chrome or firefox)
Also is it possible to use firefox sync?

I assume answers are no, but better ask.

**Comment by plateaukao** [comment]
@gety9 No, it's not possible to install extensions. In order to be able to install extensions, I need to integrate the extension mechanism from either Chrome or Firefox. Firefox is using a different rendering engine, so maybe I have to re-write the whole app to use its engine to make it possible. As for Chrome extensions, I haven't studied yet, but the integration effort would be large, and.. the integration size may be much larger than this app current size. If you know any open source app that support Chrome extensions, you can let me know, and maybe I can take a look at it still. :)

**Comment by gety9** [comment]
@plateaukao 
I see, thank you for explanation. I am not sure if adding FF/Chrome extension mechanism is worth it if it will result in much bigger app size cause einkbro's speed is one of it's important strengths.
Closing for now.

**Comment by alanjsebas** [comment]
What about userscripts?

**Comment by plateaukao** [comment]
I tried finding open source project that helps to integrate userscript, but there's few and incomplete. To support it all by myselft may need efforts larger than developing EinkBro's all feature. Still, PR is welcome if anyone can help on this.
