### ISSUE TITLE
Several questions. 

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#63]
Have several questions, didn't find answers to them in neither read.me not opened/closed issues so positing here:

1. Sometimes tool bar (bottom right) seems to disappear for me and I see only title of the page (bottom left), nothing I try brings toolbar back - only closing / reopening app works. Am I pressing something accidently or is it a bug?
2. When pressing on tab I see 3 + icons:
'+ on black square, + secured and regular +.
1st seem to open new browser window, but what is the difference between 2nd and 3rd?
3. Does einkbro uses some kind of cache for pages?
Cause when I added comment to GitHub issue and revisited issue later my comment was not shown. I assumed maybe it didn't post... I refreshed page 2 times and finally saw it.
4. Do I understand it right that there is no next / previous tab buttons for toolbar?
5. Is there a full list of short-cuts (for when I connect my keyboard) ? For example Ctrl + t new tab, etc.

p.s. one more time thanks for great work. I really like einkbro.

**Comment by plateaukao** [comment]
1. That's because toolbar is with scroll feature. When title is too long, you can horizontally scroll the tool bar to see other buttons. It happens often if you rotate the device screen. You can configure the toolbar to show only a "pen" button, without adding the title, it's more convenient if you add many buttons.
2. first + is open new browser window, that you can find it in system recent app list (useful if you know how to activate system multi-window feature); second + is open an incognito tab, the third is just normal tab. :)
3. a little bit cache is enabled (so that when you press back, it won't reload all contents again). If you reload the page, it should always get the latest content.
4. Currently, no. In the past, it's possible to use gesture to navigate among tabs, but after adding too many function buttons, the feature is gone.
5. Yes, it's in https://github.com/plateaukao/browser/blob/main/CHANGELOG.md. Please check notes for v8.0. Maybe I should add a page in App to describe what are supported. :D

Glad that it's useful to you. :)

**Comment by gety9** [comment]
@plateaukao 
thank you for replies. In "1." i think it's different issue cause for same page (with medium title which works pefectly / have enough space to display all toolbar) after this "bug state" is triggered it does not display anything on the right (no icons at all /just empty space).

I tried scrolling it - but it's not scrollable either. (maybe cause i have big screen - 10.3")

What seems to be triggering this state is unplugging (or plugging in) physical keyboard while entering url address. (Basically changing input keyboard)

**Comment by plateaukao** [comment]
Thanks for the more detail description. I have 10.3" device too(Onyx BOOX Note3). May I know what input method you are using, and what website you are browsing when the issue happens? it'll be helpful for me to reproduce the issue.

**Comment by gety9** [comment]
@plateaukao 
Seems like 1. was "hide toolbar" feature. And icon for show again (buttom right corner) was not very noticable  so didn't understand what's going on :)

Now i disabled "hide toolbar" feature and it works perfect for my needs.

One more time thank you for great app, great support / fast responses.

**Comment by gety9** [comment]
@plateaukao 

Daniel, could you please tell

1. what settings determine the size of font of the webpages? Are there any settings beside font size / bold? I am asking cause today when i reinstalled the Einkbro text on pages looked exactly like before uninstall, but when i reopened the einkbro text looked much smaller, and i didn't change anything.
(i mean text on web page, not toolbar)
2. when i change font size / boldness i can see effect only on reload, is it how it supposed to work?
3. you also have 10.3" device, what font size / boldness do you find most comfortable?

**Comment by plateaukao** [comment]
1. web pages determine their own font sizes. In browser, browser can scale web page font by percentage.
> Are there any settings beside font size / bold?
No, I guess I only support these two attribute change. Onyx BOOX devices can modify App font settings too. Not sure if it's caused by device per-app settings.
2. No, web page font size should be updated right away.
3. it depends on web content. On average, I found 125% is fine for me most of the times.

**Comment by gety9** [comment]
@plateaukao 
thank you for explanation.

**Comment by plateaukao** [comment]
1. no, now it's not possible to do so. I'll consider it in future versions.
2. The bookmarks list is sorted in alphabetical order. I often add a 0 in the name of the bookmark so it would be displayed in bottom. 
3. For frequently used sites, I'll just create shortcuts on Home screen.
