### ISSUE TITLE
Lollipop?

### ISSUE THREAD

**Issue by bohwaz** [plateaukao/browser#8]
Yotaphone is kind of stuck on Lollipop I think. Is there any chance to add Lollipop support?

**Comment by plateaukao** [comment]
I'll try to support Lollipop in next version.

**Comment by FanZhen2002** [comment]
My sony rp1 is also android 5.0.  thanks in advance

**Comment by plateaukao** [comment]
@bohwaz , @FanZhen2002 

Please try version 8.7.5. https://github.com/plateaukao/browser/releases/tag/v8.7.5

**Comment by bohwaz** [comment]
That's great and quick! it works well except issue #15 

Also I miss an option to print PDF in 5" :)

Thank you very much!

**Comment by plateaukao** [comment]
Hi, @bohwaz 
Thanks for reporting the issue with log. It will be fixed in next version.

As for print PDF, it should also work on Lollipop too. 
Maybe it's because your device manufacturer does not support built-in print to pdf feature. I met similar issues in old Onyx Boox devices before. There's nothing I can do from EinkBro side.

**Comment by bohwaz** [comment]
> As for print PDF, it should also work on Lollipop too.
> Maybe it's because your device manufacturer does not support built-in print to pdf feature. I met similar issues in old Onyx Boox devices before. There's nothing I can do from EinkBro side.

It works, but I'm missing a 5" page size, as the Yotaphone e-ink screen is only 4.7" :)

Thank you!
