### ISSUE TITLE
Page Width on DrivethruRPG

### ISSUE THREAD

**Issue by MarjaE2** [plateaukao/browser#84]
Hi,

Eink Browser occasionally has trouble with page width. For example, on https://www.drivethrurpg.com/, it chops off the right side of every page. Changing from portrait to landscape doesn't help, it just enlarges everything. Changing font sizes doesn't help. Changing to text mode doesn't help either.

Having an option to resize pages to fit the width of the screen would be handy.

**Comment by plateaukao** [comment]
@MarjaE2  do you mean the desktop version of that site? If you long press on the setting button (on toolbar), and toggle Desktop mode, I think that's what you want?
Also, even if you didn't toggle desktop mode, when right side of the content is not displayed, you can still use two fingers to zoom out the content so that whole page can be seen on screen. (although you may need to turn off multi-touch feature in Settings first.)

**Comment by MarjaE2** [comment]
Thank you, desktop mode works. I can't use zooming because it gives me migraines, and also, gestures require too much coordination. One of the nice things about Eink Browser is being able to tap instead of having to scroll.
