### ISSUE TITLE
Reader Mode on by default?

### ISSUE THREAD

**Issue by kevinctofel** [plateaukao/browser#9]
I have a new eInk Android device arriving tomorrow to replace my Kindle Oasis. Love my Kindle but the browser is awful, so your app pushed me to try a different device! I plan to use it so I'm not staring at LCD panels 12 hours a day. Curious: Can Reader Mode bet set as active by default for every page and if not, is that something you'd consider as a feature request for the future?

Cheers,
kct

**Comment by plateaukao** [comment]
Hi, @kevinctofel 
Hope you enjoy your new eInk device. 
About the feature you requested, it's not totally impossible to implement it. However, the Reader Mode is not yet very mature, and as the name suggests, it will remove most un-necessary components in web content, which may include the links you need to navigate to other or next page. You still need to leave Reader mode in order to navigate among web pages in most web sites.
Secondly, to make Reader Mode work, EinkBro has to load the original web content first. After it's fully rendered, then Reader Mode can be applied. So, you will see obvious UI flash between normal web content, and reader mode for each page.
So, in near future, I tend not to support default Reader Mode. One day, if I find better Read Mode implementation (like how Brave browser does, it can support Reader Mode before the original web page is rendered), I will consider again your suggestion.

**Comment by kevinctofel** [comment]
Makes total sense. Appreciate the consideration and the technical info. Cheers!

**Comment by kevinctofel** [comment]
Got the LikeBook and immediately tried your browser. Fantastic! https://twitter.com/kevinctofel/status/1390824632287174659?s=21

**Comment by plateaukao** [comment]
Thank you for letting me know that you installed it on your LikeBook. I love LikeBook's built-in reader more than other E-ink devices because it can display ebook in vertical mode; very good for Chinese and Japanese content.
